Главная страница проекта - разметка
htmlacademy-htmlcss/1952527-sedona-33 pull request #2
Opened 2022-01-23 09:47 UTC by Naz-Vlad

Разметил главную  страниц,  сейчас , делаю каталог. Как будет готов отправлю.

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +  <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>
Это надо удалить. Оно нам не нужно больше

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +   <nav class="navigation">
Есть много проблем со стилистикой кода. Я записывал видео для одной ученицы, советую посмотреть и исправить в соответствии с этим видео всё: https://youtu.be/lvV6ly2tjs4

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +      <ul class="navigation-list navigation-user">
Убрать navigation-list

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +         <li class="navigation-item">
Это элемент в navigation-user, а не в navigation-list, соответственно можно назвать как user-item

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +           <a class="navigation-link" href="#">
А это будет user-search потому что это конкретно поиск, у этой иконки свой стиль

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +           <a class="navigation-link" href="#">
А это будет user-favorite. И да, это не отзывы, а избранное.

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +            <a class="button" href="#">ХОЧУ СЮДА</a>
Не большими буквами пишем, а просто обычным текстом "Хочу сюда"

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +   <h1 class="visully-hidden">CEDONA</h1>
Удалить, не нужно

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +
Нужен отдельный div в котором будет картинка с текстами приветственными

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +      <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Это как раз h1

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +      <ul>
Почему нет ни одного класса дальше в тегах?

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +            <img class="foto-1" src="#" alt="Описание картинки">
Нет в английском слова foto. Также нельзя называть на столько общими названиями типа foto-1. Не надо использовать такие названия. В учебнике максимально подробно рассказано про именование сущностей. https://up.htmlacademy.ru/htmlcss/33/book/1.16 нужно прочитать и применять все что тут сказано) Про числа тут тоже сказано

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +      <a class="button" href="catalog.html">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
Не нужно писать большими буквами.

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +         <input type="text" name="e-mail" placeholder="Ваш e-mail">
У каждого input должен быть label. Тут он будет скрытый и с текстом "E-mail" и всё. А сам input будет required, так как нужно в обязательном порядке его заполнить чтоб можно было форму отправить.

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +          <li class="social-item">
Это не социальная кнопка и вообще никак к social секции не относится. Надо выносить вне этой секции и делать. А сам телефон должен быть ссылкой. Опять же в учебнике есть про ссылки такого рода информация: https://up.htmlacademy.ru/htmlcss/33/book/1.15

2022-01-23 11:42 UTC, captain-zsa commented on index.html
> +          <li class="social-item">
Ровно как и это совершенно никак к social элемент не относится. Полностью отдельный со своим названием класса.

2022-01-23 20:40 UTC, Naz-Vlad commented
Не  могу форкнуть проект с замечаниями. Нажимаю на Fork, страница переключается на мой репозиторий на копии проекта нет

2022-01-25 08:08 UTC, captain-zsa reviewed
Я не проверял и не буду проверять каталог, пока главная не будет приведена в порядок. И соответственно все ошибки, которые есть на главной, надо устранять и в каталоге. Они там точно такие же.

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +      <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Почему так и не стал h1?

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +    <h1 class="visully-hidden">CEDONA</h1>
Зачем это? Ещё и написано название города неверно

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +            <img class="foto-1" src="#" alt="Описание картинки">
Не исправлено никак.

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +        <ul>
Почему нет ни одного класса ниже нигде?

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +        </ul>
Явные проблемы с табуляцией. Тут уже 4 пробела до закрывающего тега, а должно быть 2. Где-то началось и тут вот оканчивается эта ошибка.

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +      <span>
Почему так и не вынесено из секции footer-social? И тут не span, а абзац должен быть и конечно же ему нужно класс прописать.

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +      <a class="social-link" href="https://htmlacademy.ru/study">
Какой же это social-link когда это совершенно никак не относится к социальным сетям? Тоже нужно вытащить из секции footer-social

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +          <a class="social-link" href="#">
Сказано в фигме, что иконки соц сетей должны вести на страницы академии. Это необходимо сделать. Слева от макета в фигме прописано ТЗ и оно обязательно для исполнения.
<img width="662" alt="image" src="https://user-images.githubusercontent.com/18168845/150936615-2138e0cd-d515-400f-bf2f-1418343be19b.png">

2022-01-25 08:08 UTC, captain-zsa commented on index.html
> +      <a class="social-link" href="https://htmlacademy.ru/study">
И да, study нужно удалить. Опять же в ТЗ сказано что четко на страницу сайта академии должен вести их логотип.

2022-01-25 09:39 UTC, Naz-Vlad commented on index.html
> +   <nav class="navigation">
исправленно

2022-01-25 09:41 UTC, Naz-Vlad commented on index.html
> +  <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>
исправленно

2022-01-25 09:43 UTC, Naz-Vlad commented on index.html
> +      <ul class="navigation-list navigation-user">
исправлено

2022-01-25 09:45 UTC, Naz-Vlad commented on index.html
> +         <li class="navigation-item">
сейчас сделал

2022-01-25 09:49 UTC, Naz-Vlad commented on index.html
> +           <a class="navigation-link" href="#">
исправленно

2022-01-25 10:11 UTC, Naz-Vlad commented on index.html
> +            <img class="foto-1" src="#" alt="Описание картинки">
сейчас сделал

2022-01-25 10:14 UTC, Naz-Vlad commented on index.html
> +      <a class="button" href="catalog.html">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
исправлено

2022-01-25 10:15 UTC, Naz-Vlad commented on index.html
> +         <input type="text" name="e-mail" placeholder="Ваш e-mail">
исправлено

2022-01-25 10:16 UTC, Naz-Vlad commented on index.html
> +          <li class="social-item">
исправлено

2022-01-25 10:22 UTC, Naz-Vlad commented on index.html
> +          <li class="social-item">
сейчас сделал

2022-01-25 10:46 UTC, Naz-Vlad commented on index.html
> +    <h1 class="visully-hidden">CEDONA</h1>
сделал сейчас

2022-01-25 11:29 UTC, Naz-Vlad commented on index.html
> +        </ul>
сделал

2022-01-25 11:56 UTC, Naz-Vlad commented on index.html
> +      <a class="social-link" href="https://htmlacademy.ru/study">
сделал

2022-01-25 11:56 UTC, Naz-Vlad commented on index.html
> +      <span>
сделал

2022-01-25 11:59 UTC, Naz-Vlad commented on index.html
> +          <a class="social-link" href="#">
Поправил все замечания, постарался ничего не пропустить, можно ли исправленную главную страницу отправить на проверку?

2022-01-26 08:54 UTC, captain-zsa commented on index.html
> +      <h1>Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
Нет класса. И ниже у абзаца тоже. И у огромного количества тегов тоже нет класса. Это плохо.

2022-01-26 08:54 UTC, captain-zsa commented on index.html
> +        <li class="reasons-list">
Как это у li такой же класс как у ul? Так быть не может. Что ж это будет, всё что мы применим к ul применится и к li. Это ж полностью развалит макет, так как свойства им нужны разные.

2022-01-26 08:54 UTC, captain-zsa commented on index.html
> +        <li class="reasons-list">
Если коротко об этом блоке и о его разметке, как она должна быть устроена:

```
<ol class="edge-list">
  <!-- edge-item-long говорит о том что это большой блок преимущества (внизу есть с цифрами но маленькие серые) -->
  <li class="edge-item edge-item-long">
    <!--Класс edge-wrapper-blue говорит о том что этот блок будет с голубым фоном-->
    <div class="edge-wrapper edge-wrapper-blue">
      <h3 class="edge-title">Название преимущества</h3>
      <p class="edge-number">- 1 -</p>
      <p class="edge-description">Описание преимущества</p>
    </div>
    <div class="edge-image">
      <img>
    </div>
    <!-- Это подпункты от пункта, поэтому список внутри -->
    <ul class="edge-sublist">
      <li class="edge-item">
        <div class="edge-wrapper edge-wrapper-silver">
          <h4 class="edge-title">Жилье</h4>
          <p class="edge-description">Описание</p>
        </div>
      </li>
      <!-- конечно дальше ещё 2 элемента -->
    </ul>
  </li>
  <li class="edge-item edge-item-long">
    <!-- Всё тоже самое, что в предыдущем только без подпунктов -->
  </li>
  <li class="edge-item">
    <!-- Конечно вместо "цвет" надо английское название того или иного цвета, сейчас эти классы ставить не обязательно, можно на этапе стилизации это будет сделать, достаточно будет пока просто edge-wrapper и всё -->
    <div class="edge-wrapper edge-wrapper-цвет">
      <h3 class="edge-title">Название</h3>
      <p class="edge-number">- 3 -</p>
      <!-- и так далее -->
    </div>
  </li>
</ol>
```

за счет правильных названий классов у нас:
1. Придется писать намного меньше css-кода, чем в твоем случае (в твоем случае каждый класс уникален и это заставляет нас писать снова и снова один и тот же css код для каждого уникального класса)
2. Сильно понятнее по названию класса, что за элемент. Если мы в css увидим класс edge-title – мы четко понимаем что это заголовок преимущества и так как мы видели дизайн хоть даже пару раз всего, мы всё равно помним, что там где-то были преимущетсва и это именно оттуда, а какие они там были – эту подробность мы точно не вспомним. Либо если мы не работали над сайтом даже месяц – всё забывается, и вернувшись к работе над ним, увидев класс real-city-text-block-head вот вообще не понятно где там оно находится, а по edge-title всё прекрасно понятно.


> Конечно же просто брать и копировать нельзя всё что я написал, этого не достаточно будет, надо будет полностью доразмечать всё, вставить правильные тексты и тд и тп.

2022-01-26 08:54 UTC, captain-zsa commented on index.html
> +        <li class="reasons-list">
Про то, как именовать классы, можно прочитать тут: https://up.htmlacademy.ru/htmlcss/33/book/1.16

Сейчас прям тотально в 90% разметки классов просто нет и это не дело.

2022-01-27 11:32 UTC, vladpovelitsa requested changes
Есть немного замечаний, всё в пределах нормы как для первого Д.З. :)
видно, что по первой странице проделана большая работа, так держать!

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +      <img class="logo" src="#" width="139" height="70" alt="Логотип Седона">
лого должно быть обернуто в ссылку (тег <a></a>) и вести на главную страницу

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +            <a class="user-search" href="#">
думаю, для этих тегов <a> лучше переименовать класс, а то получается, что у поиска и избранного класс связан с поиском (исходя из названия), это может привести в заблуждение и Вас, и других членов команды. 
Можно использовать: 
- user-icon
- navigation-icon
- link-icon и т.д. на Ваше усмотрение

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +            </label>
тут лишний отступ, должно быть в уровень в тегом <legend>

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +                Бассейн
тут и на аналогичных radio и checkbox текст стоит обернуть в тег <span> и задать ему класс, чтобы в дальнейшем была возможность стилизовать его при изменениях состояния input`а

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +            </ul>
тут нет необходимости в использовании ul и li, оставьте только label и его содержимое

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +      </a>
в макете тут 3 иконки, у Вас вижу только 2

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +          <a href="Amara Resort & Spa.jpg">
Вы еще до этого не дошли, но раз тут ссылка на картинку, то обращу внимание сразу: названия всех файлов не должны содержать пробелы (можно заменить на тире, нижнее подчеркивание или писать в стиле camelCase) и верхний регистр (большие буквы) + обратите внимание на сам путь к картинке. Это касается и других картинок.

Если не понимаете о чем речь и как исправить - пока пропускайте, т.к. занятие по работе с изображениями - дальше по графику.

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +          </a>
в данном случае правильно будет использовать тег <a> внутри заголовка: 
`<h3 class="hotels-card-title"><a href="#"> Текст заголовка </a></h3>`

проверить какой правильную вложенность тегов можно тут https://caninclude.glitch.me/

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +        <button class="button pagination-show-more" type="button">Показать ещё</button>
лишний отступ

2022-01-27 11:32 UTC, vladpovelitsa commented on catalog.html
> +      <p class="telephone">
транслит в названии классов недопустим, замените на "phone" например или другой аналог.
тут можно обойтись без тега <p> и задать класс сразу для <a>

2022-01-27 11:32 UTC, vladpovelitsa commented on index.html
> +              </div>
в данном случае <div> не нужен, т.к. роль контейнера выполняет li ему можно присвоить все необходимые для стилизации классы. Ошибка встречается несколько раз, проверьте по всему сайту

2022-01-27 16:28 UTC, vladpovelitsa approved these changes
всё исправлено, супер!

2022-01-27 16:28 UTC, merged